### ISSUE TITLE
What should our review process look like?

### ISSUE THREAD

**Issue by natestemen** [natestemen/rudin#4]
As of now, it is @epsilon-less-than-0 and I working on this we haven't been using anything of a review process besides kind of just looking over things (if that). This isn't how it really should be done, and is especially not good if anyone else wants to contribute because they won't have committing access to the master branch.

I propose that we have a branch for each section of the book. Once we have finished a section, we put together a pull request and assign it to the either myself or @epsilon-less-than-0. The reviewer will be responsible for reading over the content and making sure it is clear and pedagogical, among other things (like being error free, but the PR author should have already done this). This may not be the most ideal solution, but it is better than both of us committing to master and not having a good review process.

We could also have branches for each chapter, then have larger pull requests, but I kind of like the idea of having smaller pull requests. Easier to review and takes much less time.

@epsilon-less-than-0 what are you're thoughts?

**Comment by epsilon-less-than-0** [comment]
i think if are to make separate branches for different parts of the book, as a way to facilitate peer review, I think it's better to do it at the section level, rather than at the chapter level. Since I think individual sections present a reasonable size to review on one sitting. 

We can just start by creating separate branches from now on when we complete a section.

**Comment by natestemen** [comment]
Okay this sounds good to me. In order to facilitate this I have moved all of the content we have written to branches so that we can implement this review process ASAP.

I suggest we use the following naming convention for branches
```
num-keyword
```
where `num` is the chapter number (`0n` if `n < 10`), and `keyword` is one word that best describes that chapter. It is okay if it is not the best description, but try and be descriptive with one word.

So just from now on make sure that we write to correct branch when working on a section. @epsilon-less-than-0 

#### TO-DO
 - write this up in the contributing file.

**Comment by natestemen** [comment]
cc @epsilon-less-than-0 this is our previous conversation about the review process, just as a refresher since it's been a while. I'll add some of these ideas to our [contributing file](https://github.com/natestemen/rudin/blob/master/.github/CONTRIBUTING.md) and open a PR later.
