### ISSUE TITLE
Compiling with latexmk gives "biber" error 

### ISSUE THREAD

**Issue by epsilon-less-than-0** [natestemen/rudin#5]
```
sh: 1: biber: not found
Latexmk: Errors, so I did not complete making targets
Latexmk: Failure to make the files correctly
    ==> You will need to change a source file before I do another run <==
Collected error summary (may duplicate other messages):
  biber 00-finite-countable-and-uncountable-sets: Could not open biber log file for '00-finite-countable-and-uncountable-sets'

=== Watching for updated files. Use ctrl/C to stop ...
^CLatexmk: User typed ctrl/C or ctrl/break.  I'll finish.
Collected error summary (may duplicate other messages):
  biber 00-finite-countable-and-uncountable-sets: Could not open biber log file for '00-finite-countable-and-uncountable-sets'
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
```

**Comment by natestemen** [comment]
It looks like you maybe don't have biblatex. If you run `which biblatex` or `which biblatex8`, what does that output?

If you didn't install full texlive, maybe it didn't come with it. Perhaps try following the directions at https://tex.stackexchange.com/questions/55437/how-do-i-update-my-tex-distribution/55459#55459 and see if you can get it (might be as simple as running `tlmgr update --all`).

If you decide you wan't to purge your local texlive setup, try https://tex.stackexchange.com/questions/95483/how-to-remove-everything-related-to-tex-live-for-fresh-install-on-ubuntu then probably run something like `sudo apt-get install texlive-full` to get texlive full and you won't have to worry about much in the way of downloading latex things in the future.

**Comment by epsilon-less-than-0** [comment]
If I run ``` which biblatex``` or ``` which biblatex8``` I get no output. 

I believe I do have full texlive installed, via running what you said
```
sudo apt-get install texlive-full
```

**Comment by epsilon-less-than-0** [comment]
I followed suggestions on this thead [https://askubuntu.com/questions/439741/ubuntu-14-04-biblatex](url), and ran 
```
 sudo apt-get install texlive-bibtex-extra biber
```

and now latexmk is working. But one minor problem: I thought the pdf file was supposed to open automatically after compiling, but it is not doing that at the moment. I have to manually open the pdf file.

**Comment by natestemen** [comment]
I also thought the default `latexmk` command opened the pdf. Maybe it's different on linux.

That said if I run something like
```bash
latexmk -pdf -pvc main.tex
```
then it does open the pdf for me.
