### ISSUE TITLE
Change license to GPL

### ISSUE THREAD

**Issue by natestemen** [natestemen/rudin#6]
I'd suggest we should change the current license of the project to GPL. WTFPL (the one we currently have) is great, but it does kind of mean that someone could take the project, and go to some publishing company, get them to publish it without our consent and make a bunch of money off of it.

GPL would require any derivative work to also have a GPL license which is cool.

Do you have any thoughts on this @epsilon-less-than-0?

**Comment by epsilon-less-than-0** [comment]
I don't think I fully understand GPL, doesn't this still mean someone can take our stuff and publish it? But instead the published book won't be copyrighted? (i.e. they can STILL make money from selling, just that the stuff is not copyrighted, so someone else can also take it and sell it, and so on)

**Comment by natestemen** [comment]
yeah, i guess that's true. if you want to keep it as WTFPL im happy with that for now.

**Comment by epsilon-less-than-0** [comment]
but I think GPL is still better since at least if someone were to do so, they don't limit the possibility of anyone else doing the same. So let' do it.
